on:
  push:
    tags:
      - "*"

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          commit_owner: Justintime50
          commit_email: 39606064+Justintime50@users.noreply.github.com
          homebrew_owner: Justintime50
          homebrew_tap: homebrew-formulas
          install: 'bin.install "src/secure-browser-kiosk.sh" => "secure-browser-kiosk"'
          github_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
